# Generated by Django 5.1.6 on 2025-05-02 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profPic/')),
                ('coverPic', models.ImageField(blank=True, null=True, upload_to='profPic/')),
                ('bio', models.TextField(max_length=300)),
            ],
        ),
    ]
